### Информация
- *Автор*: Зитцер Данил
- *Дата*: вторник, 5 октября 2021 г., 15:29:39
- *Описание*: Краткое введение в Numpy и Matplotlib

## Numpy

In [1]:
import matplotlib.pyplot as plt
import numpy as np


plt.rcParams['figure.figsize'] = (18, 9)
plt.rcParams['font.size'] = 20

### Создание Numpy-массивов из списка

Используем функцию ``np.array`` для создания массива из списка:

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

Есть возможность указать целевой тип:

In [3]:
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

Вложенные списки конвертируются во вложенные массивы:

In [4]:
np.array([range(5) for x in range(3)])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### Создание массивов с нуля

In [5]:
np.zeros(shape=(2, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
np.ones(shape=(4, 3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full(shape=(3, 3), fill_value=3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [8]:
np.arange(0.1, 1.1, 0.1)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [9]:
np.linspace(0, 100, 6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [10]:
np.random.rand(2, 5)

array([[0.2939798 , 0.81751949, 0.59904999, 0.2711777 , 0.89575179],
       [0.66088089, 0.96414465, 0.29446749, 0.96909065, 0.72440732]])

In [11]:
np.random.randint(low=0, high=100, size=(1, 4))

array([[75, 60,  3, 29]])

### Доступ к атрибутам массива

In [12]:
x = np.random.randint(0, 10, size=(2, 3))
x

array([[1, 1, 7],
       [8, 4, 8]])

In [13]:
print(f'Количество элементов: {x.size}')
print(f'Количество измерений: {x.ndim}')
print(f'Размерность измерений: {x.shape}')
print(f'Тип данных: {x.dtype}')
print(f'Размер одного элемента: {x.itemsize} байт')
print(f'Размер массива: {x.nbytes} байт')

Количество элементов: 6
Количество измерений: 2
Размерность измерений: (2, 3)
Тип данных: int64
Размер одного элемента: 8 байт
Размер массива: 48 байт


### Индексация массивов: доступ к одному элементу

Одномерный массив:

In [14]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x[4]

4

In [16]:
x[-1]

9

Двумерный массив:

In [17]:
x = np.random.randint(0, 9, (2, 4))
x

array([[2, 1, 4, 7],
       [2, 5, 5, 6]])

In [18]:
x[0, 2]

4

In [19]:
x[-1, 2]

5

### Срезы массивов: доступ к подмассивам

Одномерный массив:

In [20]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
x[:6]

array([0, 1, 2, 3, 4, 5])

In [23]:
x[3:6]

array([3, 4, 5])

In [24]:
x[3:-2]

array([3, 4, 5, 6, 7])

Двумерный массив:

In [25]:
x = np.random.randint(0, 9, (3, 4))
x

array([[3, 4, 4, 4],
       [8, 8, 7, 8],
       [2, 6, 8, 5]])

In [26]:
x[0, :] # первая строка

array([3, 4, 4, 4])

In [27]:
x[:, 0]  # первый столбец

array([3, 8, 2])

In [28]:
x[1:, :]  # начиная со второй строки все столбцы

array([[8, 8, 7, 8],
       [2, 6, 8, 5]])

In [29]:
x[:, ::2]  # четные столбцы всех строк

array([[3, 4],
       [8, 7],
       [2, 8]])

### Изменение размеров массивов

In [30]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
x.shape

(12,)

In [32]:
y = x.reshape(4, 3)  # 4 строки и 3 столбца
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
y.shape

(4, 3)

In [34]:
z = x.reshape(2, 2, 3)  # 2 матрицы по 2 строки и 3 столбца
z

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

Добавление размерностей:

In [35]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [36]:
print(x[None, :])
print(x[np.newaxis, :])
print(np.expand_dims(x, 0))

[[0 1 2 3]]
[[0 1 2 3]]
[[0 1 2 3]]


In [37]:
print(x[:, None])
print(x[:, np.newaxis])
print(np.expand_dims(x, 1))

[[0]
 [1]
 [2]
 [3]]
[[0]
 [1]
 [2]
 [3]]
[[0]
 [1]
 [2]
 [3]]


### Конкатенация массивов

In [38]:
x = np.arange(6).reshape(3, 2)
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [39]:
np.hstack((x, x))

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [40]:
np.vstack((x, x, x))

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

### Векторизованные операции

In [41]:
x = np.arange(1000000)

#### Медлительность циклов

In [ ]:
%%timeit -n5 -r5
for i in range(len(x)):
    x[i] += 1

#### Numpy ufunc

In [ ]:
%%timeit -n5 -r5
x + 1

Реализованные в библиотеке Numpy арифметические операторы:

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|

In [ ]:
x = np.arange(10).reshape(5, 2)
x

In [ ]:
x + np.array([10, 20])

### Агрегирование

In [ ]:
x = np.random.randint(0, 100, (10, 10))
x

In [ ]:
x.min()

In [ ]:
x.min(axis=0)  # минимум по столбцам

In [ ]:
x.min(axis=1)  # минимум по строкам

Доступные в библиотеке Numpy функции агрегирования:

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |

### Маскирование

In [ ]:
x = np.random.randint(0, 100, (10, 10))
x

In [ ]:
x > 50

In [ ]:
x[x > 50]

In [ ]:
x[x < 10]

## Matplotlib

In [ ]:
import matplotlib.pyplot as plt

plt.rcParams['figure.figsize'] = (18, 9)
plt.rcParams['font.size'] = 20

### Простые линейные графики

In [ ]:
x = np.linspace(0, 10, 1000)

In [ ]:
plt.plot(np.sin(x))